
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xlphfkabmphzsveftosk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhscGhma2FibXBoenN2ZWZ0b3NrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2NzIyNTAsImV4cCI6MjA1NjI0ODI1MH0.bF3GuDP_c7k5421q8d0eYzrXPIPja0Ihu4Vw03EoCbg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
